export class Member {
_id?:any;
m_name?:string;
gym_id?:string;
email?:string;
aadhar?:string;
mobile?:string;
Emergency_mobile?:string;
m_address_lat?:string;
m_address_long?:string;
memberType?:string;
m_joindate?:string;
m_accesstype?:string;
isInviteAccepted?:string;
m_startdate?:string;
m_enddate?:string;
m_validdays?:string;
m_intime?:string;
m_outtime?:string;
isAttended?:boolean;
isSetReminder?:boolean;
creation_dt?:string;
}